server:
  port: 8081

# Spring Boot
spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_NAME:graphql-demo}
    username: ${DB_USER:your-username}
    password: ${DB_PASSWORD:your-password}
    driver-class-name: org.postgresql.Driver

# Spring Boot Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

# GraphQL Voyager
voyager:
  enabled: true
  cdn:
    enabled: false

# GraphQL Playground
graphql:
  playground:
      enabled: true
      cdn:
        enabled: false