server:
  port: 8081

# Spring Boot
spring:
  datasource:
    url: jdbc:postgresql://192.168.0.202:5432/graphql-demo
    username: cubetiq
    password: cubetiq007
    driver-class-name: org.postgresql.Driver

# Spring Boot Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

# GraphQL Voyager
voyager:
  enabled: true
  cdn:
    enabled: false

# GraphQL Playground
graphql:
  playground:
      enabled: true
      cdn:
        enabled: false